[[redirects]]
  from = "hrr-gdz-9-klass-geometriya-slovo.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "hrr-sochinenie-samye-interesnye-stranicy-romana-i-s-turgenea-otcy-i-deti-nachalo-ob-avtore-serdina-o-tom-kakaya-st-ponravilas-konec-chto-pouchit.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "hrr-gdz-po-matematike-5-klass-uchebnik-2005.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "hrr-gdz-po-angliyskomu-yu-e-vaulina-6-klass.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "hrr-tayny-bermudskogo-treugolnika-referat.html"
  to = "/"
  status = 301
  force = true




